// Mapping images to keys for other modules access

export const disasterImages: { [key: string]: any }  = {
    publicViolence: require('../assets/images/emergencyImages/PublicViolence.png'),
    avalanche: require('../assets/images/emergencyImages/Avalanche.png'),
    biohazardExposure: require('../assets/images/emergencyImages/BiohazardExposure.png'),
    drought: require('../assets/images/emergencyImages/Drought.png'),
    earthquake: require('../assets/images/emergencyImages/Earthquakes.png'),
    explosion: require('../assets/images/emergencyImages/Explosion.png'),
    extremeHeat: require('../assets/images/emergencyImages/ExtremeHeat.png'),
    flood: require('../assets/images/emergencyImages/Flood.png'),
    chemicalsAndHazardousMaterials: require('../assets/images/emergencyImages/ChemicalsAndHazardousMaterials.png'),
    houseFires: require('../assets/images/emergencyImages/HouseFires.png'),
    hurricane: require('../assets/images/emergencyImages/Hurricane.png'),
    landslide: require('../assets/images/emergencyImages/Landslide.png'),
    radiation: require('../assets/images/emergencyImages/Radiation.png'),
    powerOutage: require('../assets/images/emergencyImages/PowerOutage.png'),
    thunderstormsAndLightning: require('../assets/images/emergencyImages/ThunderstormsAndLightning.png'),
    tornado: require('../assets/images/emergencyImages/Tornado.png'),
    spaceWeather: require('../assets/images/emergencyImages/SpaceWeather.png'),
    tsunami: require('../assets/images/emergencyImages/Tsunamis.png'),
    volcano: require('../assets/images/emergencyImages/Volcanoes.png'),
    wildfire: require('../assets/images/emergencyImages/Wildfire.png'),
    winterWeather: require('../assets/images/emergencyImages/WinterWeather.png'),
    sandStorm: require('../assets/images/emergencyImages/SandStorm.png'),
    epidemic: require('../assets/images/emergencyImages/Epidemic.png')
}

export const firstAidImages: { [key: string]: any } = {
    allergicReaction: require('../assets/images/firstAidImages/AllergicReaction.png'),
    asthmaAttack: require('../assets/images/firstAidImages/AsthmaAttack.png'),
    bleedingHeavily: require('../assets/images/firstAidImages/BleedingHeavily.png'),
    brokenBone: require('../assets/images/firstAidImages/BrokenBone.png'),
    burn: require('../assets/images/firstAidImages/Burn.png'),
    choking: require('../assets/images/firstAidImages/Choking.png'),
    dehydration: require('../assets/images/firstAidImages/Dehydration.png'),
    diabeticEmergency: require('../assets/images/firstAidImages/DiabeticEmergency.png'),
    distress: require('../assets/images/firstAidImages/Distress.png'),
    seizure: require('../assets/images/firstAidImages/Seizure.png'),
    headInjury: require('../assets/images/firstAidImages/HeadInjury.png'),
    heartAttack: require('../assets/images/firstAidImages/HeartAttack.png'),
    heatStroke: require('../assets/images/firstAidImages/HeatStroke.png'),
    heatExhaustion: require('../assets/images/firstAidImages/HeatExhaustion.png'),
    hypothermia: require('../assets/images/firstAidImages/Hypothermia.png'),
    meningitis: require('../assets/images/firstAidImages/Meningitis.png'),
    sprain: require('../assets/images/firstAidImages/Sprain.png'),
    stroke: require('../assets/images/firstAidImages/Stroke.png'),
    poisoning: require('../assets/images/firstAidImages/Poisoning.png'),
    unresponsiveAndBreathing: require('../assets/images/firstAidImages/UnresponsiveAndBreathing.png'),
    unresponsiveAndNotBreathing: require('../assets/images/firstAidImages/UnresponsiveAndNotBreathing.png'),
    unresponsiveAndAEDAvailable: require('../assets/images/firstAidImages/UnresponsiveAndAEDAvailable.png'),
}